# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  version: 1

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'run one line script'
  
  - script: 
      echo Add other tasks to build and test
      echo See https://aka.ms/yaml
    displayName: 'run multi-line script'