# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  version: 1

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Update_version
  steps:
  - task: HelmInstaller@1
    inputs:
     helmVersionToInstall: '3.0.0'
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'AKSBlueGreen-aksrich15966-bluegreen-1597837665187'
      namespace: 'bluegreen'
      command: 'ls'